"""
Enterprise Attack Classification Engine

Classifies suspicious network flows into attack categories
using extracted flow statistics and TCP behavior.

Author: Mohit Sharma
Project: AI-Powered Intrusion Detection System
"""

from typing import Dict, Optional


class AttackClassifier:
    """
    Rule-based attack classification engine.

    Current detection categories:

        - Port Scan
        - SYN Flood / DoS
        - Brute Force
        - Suspicious TCP Activity
        - Generic Anomalous Traffic
        - None / Benign
    """

    # ============================================================
    # PUBLIC API
    # ============================================================

    @staticmethod
    def classify(
        features: Dict,
        anomaly_score: float = 0.0,
        severity: str = "Normal",
    ) -> Optional[str]:
        """
        Classify a network flow.

        Args:
            features:
                ML-ready feature dictionary generated by
                FeatureExtractor.

            anomaly_score:
                Final anomaly score produced by AnomalyScorer.

            severity:
                Severity classification.

        Returns:
            Attack type string or None.
        """

        # --------------------------------------------------------
        # Extract commonly used features
        # --------------------------------------------------------

        packet_count = features.get("packet_count", 0)
        packets_per_second = features.get(
            "packets_per_second", 0.0
        )

        syn_count = features.get("syn_count", 0)
        ack_count = features.get("ack_count", 0)
        rst_count = features.get("rst_count", 0)
        fin_count = features.get("fin_count", 0)

        syn_ack_ratio = features.get(
            "syn_ack_ratio", 0.0
        )

        rst_ratio = features.get(
            "rst_ratio", 0.0
        )

        forward_packets = features.get(
            "forward_packets", 0
        )

        backward_packets = features.get(
            "backward_packets", 0
        )

        # ========================================================
        # BENIGN TRAFFIC
        # ========================================================

        if (
            anomaly_score < 0.40
            and severity == "Normal"
        ):
            return None

        # ========================================================
        # SYN FLOOD / DoS
        # ========================================================

        if AttackClassifier._is_syn_flood(
            packet_count=packet_count,
            packets_per_second=packets_per_second,
            syn_count=syn_count,
            ack_count=ack_count,
            syn_ack_ratio=syn_ack_ratio,
        ):
            return "SYN Flood / DoS"

        # ========================================================
        # PORT SCAN
        # ========================================================

        if AttackClassifier._is_port_scan(
            syn_count=syn_count,
            ack_count=ack_count,
            rst_count=rst_count,
            forward_packets=forward_packets,
            backward_packets=backward_packets,
            anomaly_score=anomaly_score,
        ):
            return "Port Scan"

        # ========================================================
        # BRUTE FORCE
        # ========================================================

        if AttackClassifier._is_brute_force(
            packet_count=packet_count,
            packets_per_second=packets_per_second,
            syn_count=syn_count,
            rst_count=rst_count,
            anomaly_score=anomaly_score,
        ):
            return "Brute Force"

        # ========================================================
        # SUSPICIOUS TCP ACTIVITY
        # ========================================================

        if AttackClassifier._is_suspicious_tcp(
            syn_count=syn_count,
            rst_count=rst_count,
            fin_count=fin_count,
            rst_ratio=rst_ratio,
            anomaly_score=anomaly_score,
        ):
            return "Suspicious TCP Activity"

        # ========================================================
        # GENERIC ANOMALOUS TRAFFIC
        # ========================================================

        if anomaly_score >= 0.40:
            return "Generic Anomalous Traffic"

        return None

    # ============================================================
    # SYN FLOOD DETECTION
    # ============================================================

    @staticmethod
    def _is_syn_flood(
        packet_count: int,
        packets_per_second: float,
        syn_count: int,
        ack_count: int,
        syn_ack_ratio: float,
    ) -> bool:
        """
        Detect high-volume SYN-heavy traffic.

        This is intentionally conservative because a real
        production IDS should use additional temporal and
        destination-based evidence.
        """

        if packet_count < 20:
            return False

        if packets_per_second < 10:
            return False

        if syn_count < 10:
            return False

        # Large SYN/ACK imbalance
        if syn_ack_ratio > 3:
            return True

        # Very high SYN count with insufficient ACKs
        if syn_count >= 20 and ack_count < syn_count:
            return True

        return False

    # ============================================================
    # PORT SCAN DETECTION
    # ============================================================

    @staticmethod
    def _is_port_scan(
        syn_count: int,
        ack_count: int,
        rst_count: int,
        forward_packets: int,
        backward_packets: int,
        anomaly_score: float,
    ) -> bool:
        """
        Detect suspicious TCP probing behavior.

        Current rule focuses on SYN-heavy flows with limited
        response traffic.
        """

        if syn_count < 3:
            return False

        if anomaly_score < 0.40:
            return False

        # SYN-heavy traffic with very few ACKs
        if syn_count > ack_count * 2:
            return True

        # Strong forward/backward imbalance
        if forward_packets >= 5 and backward_packets <= 2:
            return True

        # SYN + RST probing behavior
        if rst_count >= 2 and syn_count >= 3:
            return True

        return False

    # ============================================================
    # BRUTE FORCE DETECTION
    # ============================================================

    @staticmethod
    def _is_brute_force(
        packet_count: int,
        packets_per_second: float,
        syn_count: int,
        rst_count: int,
        anomaly_score: float,
    ) -> bool:
        """
        Detect repeated rapid connection attempts.

        This is a network-level heuristic and should eventually
        be combined with authentication/log data.
        """

        if anomaly_score < 0.50:
            return False

        if packet_count < 15:
            return False

        if packets_per_second < 3:
            return False

        if syn_count >= 5:
            return True

        if rst_count >= 5:
            return True

        return False

    # ============================================================
    # SUSPICIOUS TCP
    # ============================================================

    @staticmethod
    def _is_suspicious_tcp(
        syn_count: int,
        rst_count: int,
        fin_count: int,
        rst_ratio: float,
        anomaly_score: float,
    ) -> bool:
        """
        Detect unusual TCP flag behavior.
        """

        if anomaly_score < 0.40:
            return False

        if rst_ratio >= 0.50:
            return True

        if syn_count >= 5 and fin_count == 0:
            return True

        if rst_count >= 3:
            return True

        return False

    # ============================================================
    # MITRE ATT&CK MAPPING
    # ============================================================

    @staticmethod
    def mitre_technique(
        attack_type: Optional[str],
    ) -> Optional[str]:
        """
        Map detected attack category to a MITRE ATT&CK technique.
        """

        mapping = {
            "Port Scan": "T1046",
            "SYN Flood / DoS": "T1498",
            "Brute Force": "T1110",
            "Suspicious TCP Activity": None,
            "Generic Anomalous Traffic": None,
        }

        return mapping.get(attack_type)

    # ============================================================
    # CLASSIFICATION DETAILS
    # ============================================================

    @staticmethod
    def classify_with_details(
        features: Dict,
        anomaly_score: float = 0.0,
        severity: str = "Normal",
    ) -> Dict:
        """
        Return attack classification together with
        MITRE ATT&CK mapping and malicious label.
        """

        attack_type = AttackClassifier.classify(
            features=features,
            anomaly_score=anomaly_score,
            severity=severity,
        )

        mitre = AttackClassifier.mitre_technique(
            attack_type
        )

        label = (
            "Malicious"
            if attack_type is not None
            else "Benign"
        )

        return {
            "attack_type": attack_type,
            "mitre_technique": mitre,
            "label": label,
        }